name = "Cubature"
uuid = "667455a9-e2ce-5579-9412-b964f529a492"
version = "1.5.1"

[deps]
Cubature_jll = "7bc98958-0e37-5d67-a6ac-a3a19030071a"

[compat]
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
